# Generated by Django 4.2.14 on 2024-08-07 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('visitor_count', models.IntegerField(default=0)),
                ('response_count', models.IntegerField(default=0)),
                ('is_private', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=50, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.form')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('linear', 'linear'), ('free', 'free')], max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('is_private', models.BooleanField(default=False)),
                ('visitor_count', models.IntegerField(default=0)),
                ('response_count', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=50, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.category')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('select', 'select'), ('checkbox', 'checkbox'), ('text', 'text')], max_length=20)),
                ('metadata', models.JSONField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.form')),
            ],
            options={
                'unique_together': {('name', 'form')},
            },
        ),
        migrations.CreateModel(
            name='FormProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.form')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.process')),
            ],
            options={
                'unique_together': {('order', 'process', 'form')},
            },
        ),
    ]
