# Generated by Django 4.2.14 on 2024-08-03 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('visitor_count', models.IntegerField(default=0)),
                ('response_count', models.IntegerField(default=0)),
                ('is_private', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('linear', 'linear'), ('free', 'free')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('is_private', models.BooleanField(default=False)),
                ('visitor_count', models.IntegerField(default=0)),
                ('response_count', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('select', 'select'), ('checkbox', 'checkbox'), ('text', 'text')], max_length=20)),
                ('description', models.JSONField(max_length=511)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(max_length=511)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.form')),
            ],
        ),
    ]
