# Generated by Django 4.2 on 2024-08-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='responder_nickname',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
