# Generated by Django 4.2 on 2024-08-09 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0002_alter_form_category_alter_form_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='forms',
            field=models.ManyToManyField(blank=True, related_name='categories', to='forms.form'),
        ),
        migrations.AddField(
            model_name='category',
            name='processes',
            field=models.ManyToManyField(blank=True, related_name='categories', to='forms.process'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='form',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.category'),
        ),
        migrations.AlterField(
            model_name='form',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formprocess',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.form'),
        ),
        migrations.AlterField(
            model_name='formprocess',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.process'),
        ),
        migrations.AlterField(
            model_name='process',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.form'),
        ),
        migrations.AlterField(
            model_name='response',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.form'),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
