# Generated by Django 4.2.14 on 2024-08-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
