# Generated by Django 4.2.14 on 2024-08-05 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_form_password_alter_process_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.category'),
        ),
    ]
