# Generated by Django 4.2.14 on 2024-08-11 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0003_category_forms_category_processes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='forms',
        ),
        migrations.RemoveField(
            model_name='category',
            name='processes',
        ),
        migrations.RemoveField(
            model_name='process',
            name='is_private',
        ),
        migrations.AddField(
            model_name='process',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.category'),
        ),
        migrations.AlterUniqueTogether(
            name='formprocess',
            unique_together={('order', 'process')},
        ),
    ]
